# Generated by Django 2.0.7 on 2018-09-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catequista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data Nascimento')),
                ('data_inicio', models.DateField(verbose_name='Data Início')),
                ('status', models.BooleanField(verbose_name='Status')),
            ],
        ),
    ]
