# Generated by Django 2.0.7 on 2018-09-19 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catequista', '0001_initial'),
        ('crismando', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenca', models.BooleanField(default=False, verbose_name='Presença')),
                ('data_encontro', models.DateField(verbose_name='Data Encontro')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('crismando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crismando.Crismando', verbose_name='Crismando')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catequista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catequista.Catequista', verbose_name='Catequista')),
                ('crismando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crismando.Crismando', verbose_name='Crismando')),
            ],
        ),
    ]
