# Generated by Django 2.0.7 on 2018-09-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crismando', '0001_initial'),
        ('catequista', '0001_initial'),
        ('crisma', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encontro',
            name='crismando',
        ),
        migrations.AddField(
            model_name='encontro',
            name='crismando',
            field=models.ManyToManyField(to='crismando.Crismando', verbose_name='Crismando'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='catequista',
        ),
        migrations.AddField(
            model_name='turma',
            name='catequista',
            field=models.ManyToManyField(to='catequista.Catequista', verbose_name='Catequista'),
        ),
        migrations.RemoveField(
            model_name='turma',
            name='crismando',
        ),
        migrations.AddField(
            model_name='turma',
            name='crismando',
            field=models.ManyToManyField(to='crismando.Crismando', verbose_name='Crismando'),
        ),
    ]
